### ISSUE TITLE
Built same circuit in Grok Bloch and IBM QE Circuit Composer, got different statevector and phases

### ISSUE THREAD

**Issue by Cortexelus** [JavaFXpert/grok-bloch#5]
This is my one qubit circuit:
![image](https://user-images.githubusercontent.com/2453861/72971055-e7b4dc80-3d96-11ea-8f82-ce3eddc11e7e.png)

When I build this in [grok bloch](https://javafxpert.github.io/grok-bloch/), I get this state vector, with only one value for phase:
![image](https://user-images.githubusercontent.com/2453861/72971067-f4393500-3d96-11ea-99d5-29b72f217b73.png)
![image](https://user-images.githubusercontent.com/2453861/72972082-c6ed8680-3d98-11ea-85f5-28de1c70360e.png)

But [circuit composer](https://quantum-computing.ibm.com/composer/new-experiment) gives me a phase value for each state, and the statevector is different:
![image](https://user-images.githubusercontent.com/2453861/72971193-424e3880-3d97-11ea-94b5-1414b0b37d3a.png)

The state vectors are in different formats, so let's convert to confirm they're different:
```
sqrt(0.5) * e^(i * 3pi/2) = 0-0.707i

the grok bloch statevector
[ |0⟩, |1⟩ ] = [ 0.707+0i, 0-0.707i  ] 

the circuit composer statevector
[ |0⟩, |1⟩ ] = [ 0-0.707i, -0.707+0i ]
```

And let's compare the phases

```
grok bloch phases
[ arg(0.707+0i),  arg(0-0.707i) ] = [ 0, -π/2 ] = [ 0, 3π/2 ]

circuit composer phases
[ arg(0-0.707i),  arg(-0.707+0i) ] = [ -π/2, π ]
```

Which is the correct way to grok the bloch? 
How many phases does a qubit have?

Thanks

**Comment by Cortexelus** [comment]
Each state has a phase, but in Grok Bloch I see you [subtract the phases](https://github.com/JavaFXpert/grok-bloch/blob/99e1636be1cea46258f3bb878ea83ba7d4481bad/js/blochsphere.js#L71) from the two states to get `azimuthRadians` which is used as the phase for |1⟩ while the phase for |0⟩ is zeroed

Are these two representations of state vector phases equivalent? 

Is all that matters the *relative phase* between states?

**Comment by JavaFXpert** [comment]
Bingo!

Regards,
James (Jim) Weaver

**Comment by Cortexelus** [comment]
Thanks!
